# Define a imagem base como Python 3
FROM python:3

# Define o diretório de trabalho dentro do container. 
WORKDIR /app

# Copia o arquivo carguru.py do diretório local para o /app
COPY carguru.py .

# Comando executado quando o container for iniciado
CMD ["python", "carguru.py"]
